
create table invite_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  rank text not null,
  uses integer default 0,
  max_uses integer default 1,
  created_at timestamptz default now()
);

alter table invite_codes enable row level security;

create policy "Allow public read access" on invite_codes for select using (true);
